stages:
  - despliegue

despliegue_pruebas:
  stage: despliegue
  allow_failure: false
  script:
    - mvn clean install
    - mvn install -DSkiptests
    - /opt/wildfly/bin/jboss-cli.sh --connect --controller=10.10.1.121:9990  --user=$PRUEBAS_USUARIO_WILDFLY --password=$PRUEBAS_PASSWORD_WILDFLY --command="deploy target/stage_movil_renagro-0.0.1.war --force"
  tags:
    - shell
  only:
    - pruebas

despliegue_produccion:
  stage: despliegue
  allow_failure: false
  script:
    - mvn clean install
    - mvn install -DSkiptests
    - /opt/wildfly/bin/jboss-cli.sh --connect --controller=192.168.1.20:9990  --user=$PRODUCCION_USUARIO_WILDFLY --password=$PRODUCCION_PASSWORD_WILDFLY --command="deploy target/stage_movil_renagro-0.0.1.war --force"
  tags:
    - shell
  only:
    - master
